name: Azure AKS CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Log in to Azure using service principal
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set the Azure subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          # AKS 클러스터의 리소스 그룹과 클러스터 이름을 시크릿으로 설정된 변수로 가져옵니다.
          RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}
          AKS_CLUSTER_NAME=${{ secrets.AZURE_AKS_CLUSTER_NAME }}
          
          # AKS 클러스터에 대한 자격 증명 가져오기
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME

      - name: Deploy to Azure Kubernetes Service (AKS)
        run: |
          # Kubernetes 배포 작업 예시
          kubectl apply -f kubernetes-deployment.yml
          
          # 배포 상태 확인
          kubectl get pods
